// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NogVita.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NogVita.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NogVitaDbContext))]
    [Migration("20261010200741_AddFoods")]
    partial class AddFoods
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NogVita.Domain.Auth.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_email_confirmation_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_email_confirmation_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_email_confirmation_token_user_id");

                    b.ToTable("tb_email_confirmation_token", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_refresh_token_user_id");

                    b.ToTable("tb_refresh_token", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.FollowUps.CareRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid?>("EndedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by_user_id");

                    b.Property<Guid>("NutritionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("nutritionist_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tb_care_relationship");

                    b.HasIndex("NutritionistId", "EndedAtUtc")
                        .HasDatabaseName("ix_care_relationship_nutritionist_ended");

                    b.HasIndex(new[] { "PatientId" }, "ux_care_relationship_patient_active")
                        .IsUnique()
                        .HasDatabaseName("ux_care_relationship_patient_active")
                        .HasFilter("ended_at_utc IS NULL");

                    b.ToTable("tb_care_relationship", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.FollowUps.NutritionistRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("NutritionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("nutritionist_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tb_nutritionist_request");

                    b.HasIndex(new[] { "NutritionistId", "Status" }, "ix_nutritionist_request_nutritionist_status")
                        .HasDatabaseName("ix_nutritionist_request_nutritionist_status");

                    b.HasIndex(new[] { "PatientId" }, "ix_nutritionist_request_patient_id")
                        .HasDatabaseName("ix_nutritionist_request_patient_id");

                    b.HasIndex(new[] { "PatientId" }, "ux_nutritionist_request_patient_pending")
                        .IsUnique()
                        .HasDatabaseName("ux_nutritionist_request_patient_pending")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("tb_nutritionist_request", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.Foods.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Nutrients", "NogVita.Domain.Foods.Food.Nutrients#NutrientsPer100g", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("Carbohydrate")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)")
                                .HasColumnName("nutrients_carbohydrate");

                            b1.Property<decimal?>("EnergyKcal")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)")
                                .HasColumnName("nutrients_energy_kcal");

                            b1.Property<decimal?>("Fat")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)")
                                .HasColumnName("nutrients_fat");

                            b1.Property<decimal?>("Fiber")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)")
                                .HasColumnName("nutrients_fiber");

                            b1.Property<decimal?>("Protein")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)")
                                .HasColumnName("nutrients_protein");

                            b1.Property<decimal?>("SodiumMg")
                                .HasPrecision(9, 4)
                                .HasColumnType("numeric(9,4)")
                                .HasColumnName("nutrients_sodium_mg");
                        });

                    b.HasKey("Id")
                        .HasName("pk_tb_food");

                    b.HasIndex(new[] { "Barcode" }, "ux_food_barcode")
                        .IsUnique()
                        .HasDatabaseName("ux_food_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex(new[] { "Source", "SourceReference" }, "ux_food_source_reference")
                        .IsUnique()
                        .HasDatabaseName("ux_food_source_reference");

                    b.ToTable("tb_food", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.Invitations.NutritionistInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_nutritionist_invitation");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_nutritionist_invitation_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_nutritionist_invitation_user_id");

                    b.ToTable("tb_nutritionist_invitation", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.Users.NutritionistProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CrnNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crn_number");

                    b.Property<int>("CrnRegion")
                        .HasColumnType("integer")
                        .HasColumnName("crn_region");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_nutritionist_profile");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_nutritionist_profile_user_id");

                    b.HasIndex("CrnRegion", "CrnNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_nutritionist_profile_crn_region_crn_number");

                    b.ToTable("tb_nutritionist_profile", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.Users.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("biological_sex");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("goal");

                    b.Property<int>("HeightInCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_in_cm");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_patient_profile");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_patient_profile_user_id");

                    b.ToTable("tb_patient_profile", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tb_user");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_user_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_user_email");

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("NogVita.Domain.Auth.EmailConfirmationToken", b =>
                {
                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_email_confirmation_token_users_user_id");
                });

            modelBuilder.Entity("NogVita.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_refresh_token_users_user_id");
                });

            modelBuilder.Entity("NogVita.Domain.FollowUps.CareRelationship", b =>
                {
                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_care_relationship_users_nutritionist_id");

                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_care_relationship_users_patient_id");
                });

            modelBuilder.Entity("NogVita.Domain.FollowUps.NutritionistRequest", b =>
                {
                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_nutritionist_request_users_nutritionist_id");

                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_nutritionist_request_users_patient_id");
                });

            modelBuilder.Entity("NogVita.Domain.Invitations.NutritionistInvitation", b =>
                {
                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_nutritionist_invitation_users_user_id");
                });

            modelBuilder.Entity("NogVita.Domain.Users.NutritionistProfile", b =>
                {
                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithOne("NutritionistProfile")
                        .HasForeignKey("NogVita.Domain.Users.NutritionistProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_nutritionist_profile_users_user_id");
                });

            modelBuilder.Entity("NogVita.Domain.Users.PatientProfile", b =>
                {
                    b.HasOne("NogVita.Domain.Users.User", null)
                        .WithOne("PatientProfile")
                        .HasForeignKey("NogVita.Domain.Users.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_patient_profile_users_user_id");
                });

            modelBuilder.Entity("NogVita.Domain.Users.User", b =>
                {
                    b.Navigation("NutritionistProfile");

                    b.Navigation("PatientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
